### ISSUE TITLE
i has a err like this 

### ISSUE THREAD

**Issue by hui453694187** [spyboost/angular-atmosphere#2]
ReferenceError: atmosphere is not defined
    at Object.subscribe (http://localhost:9000/scripts/services/atmosphere.js:38:18)
    at new <anonymous> (http://localhost:9000/scripts/controllers/report.js:22:34)
    at Object.invoke (http://localhost:9000/bower_components/angular/angular.js:4203:17)
    at $get.extend.instance (http://localhost:9000/bower_components/angular/angular.js:8493:21)
    at http://localhost:9000/bower_components/angular/angular.js:7739:13
    at forEach (http://localhost:9000/bower_components/angular/angular.js:331:20)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7738:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7117:13)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:6996:30)
    at compile (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:4026:9) <div data-ui-view="" class="ng-scope">

**Comment by cabelin** [comment]
You need to import atmosphere.js in your page

**Comment by ghost** [comment]
I got this error as well, but I'm building an ES6 Angular 1.5 application, meaning the way libs are added to the app is different from the traditional `<script>` tag on the index.html file.
I ran `npm install atmosphere.js --save` and `npm i angular-atmosphere --save` to get both atmosphere and  this wrapper.

On my main app file, I'm doing
`import 'atmosphere.js';
import 'angular-atmosphere';`

But when I call the subscribe method of your service, I get the same error as the other user described.

Got any suggestion?
Thanks
